
volumes:
  postgres-data:
    driver: local
  kestra-data:
    driver: local
  minio-data:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

    # SECURITY CHECK 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 10

  kestra:
    image: kestra/kestra:latest
    pull_policy: always
    # Note that this setup with a root user is intended for development purpose.
    # Our base image runs without root, but the Docker Compose implementation needs root to access the Docker socket
    user: "root"
    command: server standalone # Inicia el servidor de Kestra en modo 'todo en uno'
    volumes:
      - kestra-data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock # Permite lanzar otros contenedores 
      - /tmp/kestra-wd:/tmp/kestra-wd # Directorio temp para ejecución de tareas (tmpDir apunta aquí)
    env_file:
      - .env
      - .env_encoded
    environment:
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://postgres:5432/kestra
            driverClassName: org.postgresql.Driver
            username: kestra
            password: admin
        kestra:
          server:
            basicAuth:
              enabled: false
              username: "admin@localhost.dev" # it must be a valid email address
              password: kestra
          repository:
            type: postgres
          storage:
            type: local
            local:
              basePath: "/app/storage"
          queue:
            type: postgres
          tasks:
            tmpDir:
              path: /tmp/kestra-wd/tmp
          url: http://localhost:8080/
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_started
  minio:
    image: minio/minio
    ports:
      - "9000:9000"   # Web UI/API
      - "9001:9001"   # Admin Console
    volumes:
      - minio-data:/data
    env_file:
      - .env
    command: server /data --console-address ":9001"

