id: alerta
namespace: prod.alerts

tasks:
  - id: send_alert
    type: io.kestra.plugin.notifications.mail.MailExecution
    to: yeray624@gmail.com
    from: yeray624@gmail.com
    subject: "The workflow execution {{trigger.executionId}} failed for the flow {{trigger.flowId}} in the namespace {{trigger.namespace}}"
    host: smtp.gmail.com
    port: 465
    username: yeray624@gmail.com
    password: entzcyfvyosymrxg
    executionId: "{{ trigger.executionId }}"

triggers:
  - id: failed_prod_workflows
    type: io.kestra.plugin.core.trigger.Flow
    conditions:
      - type: io.kestra.plugin.core.condition.ExecutionStatus 
        in:
          - FAILED
          - WARNING
      - type: io.kestra.plugin.core.condition.ExecutionNamespace
        namespace: prod
        prefix: true