version: 2

models:
  - name: empleados_limpios
    description: Empleados activos con datos relevantes
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: nombre
        tests:
          - not_null
      - name: salario
        tests:
          - not_null
